// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9mh3bRuZWO3zjMPQO1SDpKNXPVhqt_GY',
    appId: '1:1057207503414:web:b7de891761aa2ba45a6697',
    messagingSenderId: '1057207503414',
    projectId: 'fir-bloc-cc525',
    authDomain: 'fir-bloc-cc525.firebaseapp.com',
    storageBucket: 'fir-bloc-cc525.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdWDQyafuTCaFhdFaUEUrpSrefwZj0QE',
    appId: '1:1057207503414:android:cf2004b6614f11505a6697',
    messagingSenderId: '1057207503414',
    projectId: 'fir-bloc-cc525',
    storageBucket: 'fir-bloc-cc525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9K9CRSaoASPIKY_VAWtBLGjljES8UgE8',
    appId: '1:1057207503414:ios:a47feb70f03532b75a6697',
    messagingSenderId: '1057207503414',
    projectId: 'fir-bloc-cc525',
    storageBucket: 'fir-bloc-cc525.appspot.com',
    iosBundleId: 'com.example.firebaseBloc',
  );
}
